### ISSUE TITLE
Why should set so many version numbers in requirements? It feels a little dangerous

### ISSUE THREAD

**Issue by NightPxy** [Isi-dev/ComfyUI-UniAnimate-W#4]
This seems to reset most of the environment

**Comment by Isi-dev** [comment]
The requirements.txt file is from the original project. You can refer to it if you still encounter dependency issues after following the instructions in the README file. I use the windows portable version of ComfyUI which has a python_embeded environment and I don't think I ever made reference to the requirements.txt file. I outlined the libraries that you need to install in the README file based on the dependency issues I faced while trying to create this wrapper.

**Comment by NightPxy** [comment]
I ran it successfully and the effect was good. Thank you for your hard work

Two small questions
1. To load the unifiedModel, we need to remove some spaces here
tools/inferences/inference_unianimate_entrance.py
unifiedModel = os.path.join(root_directory, 'checkpoints/unianimate_16f_32f_non_ema_223000.pth ')

2.If using version torch 2.3.1, it is necessary to correct the XFormger version to 0.0.27
pip install xformers==0.0.27

**Comment by Isi-dev** [comment]
It's good to know you were able to run it successfully. To your questions:
1. The space at the end was mistakenly included, but I have been loading the model successfully with the space included. Thanks for pointing it out though. I will remove the space in the repo since it's an issue in some settings.

2.  You're right about the xFormer versions' compatibility with a torch version. It's the reason I specified in the README the following:
pip install xFormers = 0.0.20 or copy torch 2.0.1 and supporting libraries and xFormer from A1111 and place in your Environment\Lib\site-packages **(or) pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118 (for pytorch==2.3.1)**
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118 will install xFormers==0.0.27 for pytorch==2.3.1.

**Comment by toyxyz** [comment]
I replaced the contents of requirements with a blank and installed it and it works fine. 

Maybe the version required isn't that strict. 

This is what my ComfyUI environment looks like. 

```
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1

numpy==1.26.4
opencv-python==4.10.0.84
pytorch_lightning==2.2.1
lightning_utilities==0.10.1
lightning_fabric==2.2.1
torchmetrics==1.3.1.post0
xformers==0.0.26
einops==0.6.0
onnxruntime==1.17.1
open-clip-torch==2.24.0
fairscale==0.4.13
easydict==1.13
imageio==2.34.1
matplotlib>=3.7.1
args
```

**Comment by Isi-dev** [comment]
> I replaced the contents of requirements with a blank and installed it and it works fine.
> 
> Maybe the version required isn't that strict.
> 
> This is what my ComfyUI environment looks like.
> 
> ```
> pytorch version: 2.3.0+cu121
> xformers version: 0.0.26.post1
> 
> numpy: 1.26.4
> opencv-python: 4.10.0.84
> pytorch_lightning: 2.2.1
> lightning_utilities: 0.10.1
> lightning_fabric: 2.2.1
> torchmetrics: 1.3.1.post0
> xformers: 0.0.26
> einops: 0.6.0
> onnxruntime: 1.17.1
> open-clip-torch: 2.24.0
> fairscale: 0.4.13
> easydict: 1.13
> imageio: 2.34.1
> matplotlib: 3.7.1
> args
> ```

The version requirements isn't strict. What matters is that the versions in your environment are compliant with each other.
